FROM nvidia/cuda:11.0-runtime-ubuntu20.04

WORKDIR /home/user

RUN apt-get update && apt-get install -y software-properties-common && add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update && apt-get install -y python3.7 python3.7-dev python3.7-distutils python3-pip curl git pkg-config cmake
 
# Set default Python version
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
RUN update-alternatives --set python3 /usr/bin/python3.7

# Install pytorch with gpu support
RUN pip3 install numpy scipy Cython
RUN pip3 install torch==1.9.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html

COPY ./api/requirements.txt /home/user/
RUN pip3 install -r requirements.txt

# Copy API code and docker folder
COPY ./api /home/user/api
COPY ./docker /home/user/docker

EXPOSE 8000

# Container entrypoint and respective arguments
ENTRYPOINT ["docker/init_api.sh"]
CMD ["newsapi"]
