FROM python:3.7.4-stretch

WORKDIR /home/user

RUN apt-get update && apt-get install -y curl git pkg-config cmake wget

# Install pytorch with cpu support
RUN pip3 install numpy scipy Cython
RUN pip3 install torch==1.9.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

COPY ./api/requirements.txt /home/user/
RUN pip install -r requirements.txt

# Copy API code and docker folder
COPY ./api /home/user/api
COPY ./docker /home/user/docker

EXPOSE 8000

# Container entrypoint and respective arguments
ENTRYPOINT ["docker/init_api.sh"]
CMD ["newsapi"]
